Update DeveloperGuide.md
AY2122S1-CS2103-W14-2/tp pull request #15
Opened 2021-09-24 02:58 UTC by frederickpek

Update details to match Track2Gather, including,
* target user profile
* value proposition
* user stories
* use cases
* non-functional requirements
* glossary

2021-09-24 03:00 UTC, frederickpek commented
This PR is yet to be finalised.
Perhaps hold on merging until more members add their parts to the the doc.

2021-09-26 07:05 UTC, wei2912 requested changes
Mostly good but I think there were a few minor typos.

2021-09-26 07:05 UTC, wei2912 commented on docs/DeveloperGuide.md
> +| `* * *` | user                                     | update contacts’ contact details without re-adding that contact| avoid re-entering existing data         |
There's a missing space before the 2nd last `|` symbol.

2021-09-26 07:05 UTC, wei2912 commented on docs/DeveloperGuide.md
> +      Use case resumes at step 2.
Should this be `4a` instead?

2021-09-26 07:16 UTC, frederickpek commented on docs/DeveloperGuide.md
> +| `* * *` | user                                     | update contacts’ contact details without re-adding that contact| avoid re-entering existing data         |
Thanks for pointing out! Has been amended.

2021-09-26 07:18 UTC, frederickpek commented on docs/DeveloperGuide.md
> +      Use case resumes at step 2.
It should be 3a too. The `edit` command takes in an index and tags to modify. This extension takes care of invalid inputs to the latter.

2021-09-26 13:50 UTC, wei2912 commented on docs/DeveloperGuide.md
> +      Use case resumes at step 2.
As discussed shld be `3b` which I see has been changed alr, closing.

My apologies for the previous typo, my brain was not processing the use case lol

2021-09-26 13:50 UTC, frederickpek commented on docs/DeveloperGuide.md
> +      Use case resumes at step 2.
I have amended it to 3b instead.

2021-09-26 13:51 UTC, merged