Docs ug fred v1.4
AY2122S1-CS2103-W14-2/tp pull request #207
Opened 2021-10-31 15:24 UTC by frederickpek

All of my issues resolved, except inserting images. Will be added once ug is finalised.

2021-10-31 15:55 UTC, lrnshk requested changes
Some changes needed. @jennibearduit should refer to the `Format for person details` when changing her error messages.

2021-10-31 15:55 UTC, lrnshk commented on docs/UserGuide.md
> +`CASE_NUMBER` | Case number should be a positive integer with no leading zeros and at most 6 digits long.
Case number should be input as a positive integer with no leading zeros. It can be anywhere from 1 to 6 digits long. Note that case number is displayed in a fixed format of 6 digits, padded with zeros on the left, if needed.

2021-10-31 15:55 UTC, lrnshk commented on docs/UserGuide.md
> +`PHONE_NUMBER` | Phone numbers should only contain numbers, and it should be at least 3 digits long.
Phone numbers should only contain numbers and should be at least 3 digits long.

2021-10-31 15:55 UTC, lrnshk commented on docs/UserGuide.md
> +  * individual words will be matched e.g. Han will not match Hans
Maybe extra example here

2021-10-31 15:55 UTC, lrnshk commented on docs/UserGuide.md
> +* `find cn/1` will only match the following case numbers: `1`
number instead of numberS

2021-10-31 15:55 UTC, lrnshk commented on docs/UserGuide.md
> +* `find sh/start:2021-01-01` will only match the following SHN start dates: `2021-01-01`
date instead of dateS

2021-10-31 15:55 UTC, lrnshk commented on docs/UserGuide.md
> +* `find sh/end:2021-01-02` will only match the following SHN end dates: `2021-01-02`
date instead of dateS

2021-10-31 15:55 UTC, lrnshk commented on docs/UserGuide.md
> +* Direction `asc` indicates ascending order and `dsc` indicates descending order.
Direction `asc` indicates ascending sort order and `dsc` indicates descending sort order.

2021-10-31 16:27 UTC, lrnshk requested changes

2021-10-31 16:27 UTC, lrnshk commented on docs/UserGuide.md
> +  * individual words will be matched e.g. Han will not match Hans
* full words will be matched e.g. Han will not match Hans
* individual words will be matched e.g. Alex Hans will match Alex Yeo and Hans Yeo

2021-11-01 12:41 UTC, lrnshk approved these changes
LGTM

2021-11-01 13:00 UTC, wei2912 requested changes
Few grammatical errors, otherwise LGTM.

2021-11-01 13:00 UTC, wei2912 commented on docs/UserGuide.md
> +`NAME` | Names should only contain alphanumeric characters and spaces, and it should not be blank.
Grammatical error here, `it` is singular but `Names` is plural.

2021-11-01 13:00 UTC, wei2912 commented on docs/UserGuide.md
> +`CASE_NUMBER` | Case number should be input as a positive integer with no leading zeros. It can be anywhere from 1 to 6 digits long. Note that case number is displayed in a fixed format of 6 digits,
`Case number` should be changed to plural.

2021-11-01 13:00 UTC, wei2912 commented on docs/UserGuide.md
> +`SHN_PERIOD` | SHN period should be of two dates in the ISO-8601 format (i.e. yyyy-MM-dd), separated by a space. Start date should be keyed before the end date, and must occur earlier than the end da
It would be good to add a hyperlink to the ISO format.

2021-11-01 13:00 UTC, wei2912 commented on docs/UserGuide.md
> +`NEXT_OF_KIN_NAME` | Names should only contain alphanumeric characters and spaces, and it should not be blank.
"it" is singular

2021-11-01 13:00 UTC, wei2912 commented on docs/UserGuide.md
> +* The shift will only be applied to the persons list currently being displayed
Perhaps `persons list currently being displayed` can be changed to `persons which are currently displayed in the UI`, which might be more idiomatic

2021-11-01 14:03 UTC, wei2912 commented on docs/UserGuide.md
> +`CASE_NUMBER` | Case numbers should be input as a positive integer with no leading zeros. Case numbers can be anywhere from 1 to 6 digits long. Note that case numbers are displayed in a fixed format
"input as a positive integer" should be "input as positive integers"

2021-11-01 14:06 UTC, wei2912 requested changes
Sorry lol got more changes

2021-11-01 14:06 UTC, wei2912 commented on docs/UserGuide.md
> +`NAME` | Names should only contain alphanumeric characters, spaces and should not be blank.
Might be clearer to write "alphanumeric characters and spaces, and"

2021-11-01 14:12 UTC, wei2912 approved these changes
LGTM!

2021-11-01 14:33 UTC, merged