Improve User Guide to fix PED issues
AY2122S1-CS2103-W14-2/tp pull request #209
Opened 2021-10-31 15:36 UTC by lrnshk

Fixes #171, #199, #170, #177, #166, #157, #166

2021-10-31 16:02 UTC, frederickpek requested changes
Minor changess

2021-10-31 16:02 UTC, frederickpek commented on docs/UserGuide.md
> +  * The number of failed contact attempts recorded is cumulative over the entire period of Track2Gather usage. It does not reset to zero when a new SHN enforcement session is created.
Perhaps "contact" can be replaced with "call".

2021-10-31 16:11 UTC, frederickpek approved these changes
Looks good to merge!

2021-11-01 12:45 UTC, wei2912 commented on docs/UserGuide.md
> +In SHN enforcement mode, all people who have been called for the current SHN enforcement session will be *filtered away from the schedule and thus the display i.e. they will not show up on the interf
Think this line can be simplified, e.g. "filtered out of the schedule and be hidden on the interface" perhaps? Can't really think of a better phrasing now tbh

2021-11-01 12:46 UTC, wei2912 commented on docs/UserGuide.md
> +Under Call Status for each person, there are two components:
`Call Status` can be enclosed in quotes to indicate that it is a heading in the UI.

2021-11-01 12:51 UTC, wei2912 commented on docs/UserGuide.md
> +* If Track2Gather is in enforcement mode, the person at the specified index will be removed from the schedule and thus the display.
It might be good to add the point on the call status being updated here, as a subpoint.

2021-11-01 12:51 UTC, wei2912 commented on docs/UserGuide.md
> +* If Track2Gather is in SHN enforcement mode, the person at the specified index will be removed from the schedule and thus the display.
Same as previous comment.

2021-11-01 12:51 UTC, wei2912 requested changes
Have a few minor changes, otherwise LGTM!

2021-11-01 14:01 UTC, wei2912 approved these changes
LGTM!

2021-11-01 14:34 UTC, merged