Update README.md
AY2122S1-CS2103-W14-2/tp pull request #237
Opened 2021-11-05 05:40 UTC by frederickpek

Repo README.md not updated with latest landing page index.md, lets update it.

Include also, updated track2gather_32.png file.

This PR fixes #208 and fixes #235.

2021-11-05 06:07 UTC, jennibearduit requested changes
LGTM, minor suggestion.

2021-11-05 06:07 UTC, jennibearduit commented on README.md
> +  * next-of-kin information
Is it possible to add the word "enforce" somewhere here?

2021-11-05 06:28 UTC, frederickpek commented on README.md
> +  * next-of-kin information
This is a good suggestion! Perhaps we could bring this up again in Saturday's meeting.

I will leave this as it is becuse its only to reflect the landing page changes.

2021-11-05 08:05 UTC, jennibearduit commented on README.md
> +  * next-of-kin information
Ok sure!

2021-11-07 04:38 UTC, jennibearduit approved these changes
LGTM!

2021-11-07 04:39 UTC, merged