Add more enforcement tests
AY2122S1-CS2103-W14-2/tp pull request #248
Opened 2021-11-05 12:28 UTC by jennibearduit

- Fixed tests from previous PR
- Add new tests for enforcement

2021-11-06 13:20 UTC, over-fitted requested changes
Overall: Well done! Much improved coding style with the use of TestUtil and logically blocks. All changes requested for enforcement tests have been done properly save for what has been commented.

After this PR, please remember to do the findCommandParser changes as well as requested yesterday

2021-11-06 13:20 UTC, over-fitted commented on src/test/java/seedu/track2gather/logic/commands/FCallCommandTest.java
> +    public void execute_validIndexEnforcementMode_removedFromFilteredList() throws CommandException {
I think you should change the name to match the naming conventions of the others

2021-11-06 13:20 UTC, over-fitted commented on src/test/java/seedu/track2gather/logic/commands/FCallCommandTest.java
> +        filteredModel.updateFilteredPersonList(Model.PREDICATE_SHOW_NON_CALLED);
The filtered model should apply the Model.PREDICATE_SHOW_NON_CALLED before executing the command. This would more closely resemble the workflow of enforcement mode

2021-11-06 13:20 UTC, over-fitted commented on src/test/java/seedu/track2gather/logic/commands/FCallCommandTest.java
> +        assertFalse(firstPerson.equals(firstFilteredPerson));
While this confirms that the filtered model first person is different from that of the non-filtered model, it does not test 2 characteristics:

1) confirming that the first person is not in the filtered model at all (what if they appear at a later index)
2) confirming that the rest of the filtered model is the same as the unfiltered model minus first person

2021-11-06 13:20 UTC, over-fitted commented on src/test/java/seedu/track2gather/logic/commands/SCallCommandTest.java
> +    public void execute_validIndexEnforcementMode_removedFromFilteredList() throws CommandException {
Same as above, please adjust the name to match naming conventions

2021-11-06 13:20 UTC, over-fitted commented on src/test/java/seedu/track2gather/logic/commands/SCallCommandTest.java
> +        filteredModel.updateFilteredPersonList(Model.PREDICATE_SHOW_NON_CALLED);
same as with fcall, please change the sequence between predicate application and command execution

2021-11-06 13:20 UTC, over-fitted commented on src/test/java/seedu/track2gather/logic/commands/SCallCommandTest.java
> +        assertFalse(firstPerson.equals(firstFilteredPerson));
same as with fcall, please add the 2 additional checks

2021-11-06 13:20 UTC, over-fitted commented on src/test/java/seedu/track2gather/logic/commands/ScheduleCommandTest.java
>      public void execute_allCalledFilteredList_showEmptySchedule() {
please adjust the name to match naming conventions

2021-11-06 13:20 UTC, over-fitted commented on src/test/java/seedu/track2gather/logic/commands/ScheduleCommandTest.java
>      public void execute_allCalledUnfilteredList_showEmptySchedule() {
please adjust the name to match naming conventions

2021-11-06 13:20 UTC, over-fitted commented on src/test/java/seedu/track2gather/logic/commands/ScheduleCommandTest.java
>      public void execute_differentCallStatusFilteredList_showsDifferentSchedule() {
please adjust the name to match naming conventions

2021-11-06 13:20 UTC, over-fitted commented on src/test/java/seedu/track2gather/logic/commands/ScheduleCommandTest.java
>      public void execute_differentCallStatusUnfilteredList_showsDifferentSchedule() {
please adjust the name to match naming conventions

2021-11-06 13:20 UTC, over-fitted commented on src/test/java/seedu/track2gather/logic/commands/ScheduleCommandTest.java
>      public void execute_allNonCalledFilteredList_showsAllUncalled() {
please adjust the name to match naming conventions

2021-11-06 13:20 UTC, over-fitted commented on src/test/java/seedu/track2gather/logic/commands/ScheduleCommandTest.java
>      public void execute_allNonCalledUnfilteredList_showsSameSchedule() {
please adjust the name to match naming conventions

2021-11-06 13:20 UTC, over-fitted commented on src/test/java/seedu/track2gather/logic/commands/ScheduleCommandTest.java
> +    public void execute_calledPersonsNotShown() {
please adjust the name to match naming conventions

2021-11-06 13:20 UTC, over-fitted commented on src/test/java/seedu/track2gather/logic/commands/SessionCommandTest.java
> +    public void execute_calledPersonsResetAndShown() {
please adjust the name to match naming conventions

2021-11-07 14:40 UTC, wei2912 approved these changes
Tests should follow this naming convention:

![image](https://user-images.githubusercontent.com/2070423/140649604-ddcea85a-53ec-4c4a-ad68-1b2858d1ea02.png)

As for positive tests, it would be good if we can stick to `success()` as the expected behaviour, unless the test checks for some overall behaviour of a command. Otherwise LGTM!

2021-11-07 14:40 UTC, wei2912 commented on src/test/java/seedu/track2gather/logic/commands/ScheduleCommandTest.java
> +
Extra line

2021-11-07 14:40 UTC, wei2912 commented on src/test/java/seedu/track2gather/logic/commands/ScheduleCommandTest.java
> +    public void execute_calledPersons_notShown() {
Could the test name for this be more descriptive?

2021-11-07 14:40 UTC, wei2912 commented on src/test/java/seedu/track2gather/logic/commands/SessionCommandTest.java
> +    public void execute_calledPersonsResetAndShown() {
Should have an underscore here? :P

2021-11-07 14:40 UTC, wei2912 commented on src/test/java/seedu/track2gather/logic/commands/ScheduleCommandTest.java
> +    public void execute_calledPersons_notShown() {
Also doesn't fit naming conventions

2021-11-07 15:48 UTC, jennibearduit commented on src/test/java/seedu/track2gather/logic/commands/ScheduleCommandTest.java
> +    public void execute_calledPersons_notShown() {
fixed it to `execute_allCalledPersonsNotShown` which fits `featureUnderTest_expectedBehaviour()` , since the second part can be omitted. Is this better?

2021-11-07 15:49 UTC, jennibearduit commented on src/test/java/seedu/track2gather/logic/commands/SessionCommandTest.java
> +    public void execute_calledPersonsResetAndShown() {
switched it to `execute_allCalledPersonsResetAndShown()`, since second part can be omitted. Is this okay?

2021-11-07 16:42 UTC, wei2912 commented on src/test/java/seedu/track2gather/logic/commands/SessionCommandTest.java
> +    public void execute_calledPersonsResetAndShown() {
Yep thanks

2021-11-07 16:43 UTC, wei2912 approved these changes
LGTM!

2021-11-07 17:00 UTC, merged