DG: Fix assorted issues
AY2122S1-CS2103-W14-2/tp pull request #278
Opened 2021-11-07 16:22 UTC by wei2912

See Google Docs for more details.

2021-11-07 18:46 UTC, lrnshk requested changes
If you look at the rendered file, the bullet points for UC08 are spaced differently from the other use cases. So is NFRs and Glossary.

2021-11-07 18:46 UTC, lrnshk commented on docs/DeveloperGuide.md
>  ### Editing a Person
You changed Person to person for Add command but not here.

2021-11-08 04:14 UTC, wei2912 commented on docs/DeveloperGuide.md
>  ### Editing a Person
Thanks, have amended this!

2021-11-08 04:22 UTC, wei2912 commented
> If you look at the rendered file, the bullet points for UC08 are spaced differently from the other use cases. So is NFRs and Glossary.

Thanks for pointing this out, have identified the issues and fixed in my latest commit.

2021-11-08 04:42 UTC, lrnshk approved these changes
LGTM

2021-11-08 04:42 UTC, merged