Add SHN period field into AddCommand
AY2122S1-CS2103-W14-2/tp pull request #47
Opened 2021-10-08 14:23 UTC by lrnshk

No existent field for SHN period of persons in Track2Gather.

Adding SHN period field will enable tracking of SHN period.

2021-10-08 16:16 UTC, luffingluffy commented on src/main/java/seedu/address/storage/JsonAdaptedPerson.java
> +import java.util.*;
Same as above

2021-10-10 07:31 UTC, wei2912 requested changes
Looks good mostly, but I have a few comments.

2021-10-10 07:31 UTC, wei2912 commented on src/main/java/seedu/address/logic/parser/AddCommandParser.java
> +                : Optional.of(ParserUtil.parseShnPeriod(shnPeriodOptional.get()));
Could we preserve the order of the attributes so that these lines replace L63 (of old file)?

2021-10-10 07:31 UTC, wei2912 commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
> +
Same thing here, `ShnPeriod` should come after `QuarantineAddress`.

2021-10-10 07:31 UTC, wei2912 commented on src/main/java/seedu/address/model/person/Person.java
> +    private final Optional<ShnPeriod> shnPeriod;
Same as above.

2021-10-10 07:31 UTC, wei2912 commented on src/main/java/seedu/address/model/person/Person.java
> +                  Object nextOfKinName, Object nextOfKinPhone, Object nextOfKinAddress, Set<Tag> tags) {
Same as above - need to make sure the constructor isn't modified, else merging will be a nightmare.

2021-10-10 07:31 UTC, wei2912 commented on src/main/java/seedu/address/storage/JsonAdaptedPerson.java
> +                        : Optional.of(new ShnPeriod(shnPeriod));
Please add a blank line after this, thanks!

2021-10-10 07:31 UTC, wei2912 commented on src/test/java/seedu/address/model/person/ShnPeriodTest.java
> +    }
@over-fitted What's your opinion on the tests being structured in this manner? I was thinking that it might be better to segregate these into separate test methods, but I'm not sure if that would be necessary.

2021-10-10 07:36 UTC, wei2912 commented on src/main/java/seedu/address/storage/JsonAdaptedPerson.java
> +                        : Optional.of(new ShnPeriod(shnPeriod));
F

2021-10-10 07:38 UTC, lrnshk commented on src/main/java/seedu/address/storage/JsonAdaptedPerson.java
> +                        : Optional.of(new ShnPeriod(shnPeriod));
Oh never mind, it does.

2021-10-10 07:55 UTC, wei2912 approved these changes
LGTM for integration, will leave @luffingluffy to comment on any other matters and test writing.

2021-10-10 07:59 UTC, luffingluffy commented on src/test/java/seedu/address/model/person/ShnPeriodTest.java
> +    public void isValidShnPeriod() {
Maybe you can split this into 3 different tests?

2021-10-10 08:12 UTC, luffingluffy requested changes
The app doesn't run because I think you forgot to add the Label to the `PersonListCard.fmxl`. You can add the following line under the quarantine address label: `<Label fx:id="shnPeriod" styleClass="cell_small_label" text="\$shnPeriod"/>`

2021-10-10 08:26 UTC, luffingluffy commented on src/main/java/seedu/address/model/person/ShnPeriod.java
> +                    + "separated by a space.";
Can you add the end date must be later than the start date in the message constraint?

2021-10-10 08:35 UTC, luffingluffy approved these changes
LGTM!

2021-10-10 08:36 UTC, merged