Add work & quarantine address (WIP)
AY2122S1-CS2103-W14-2/tp pull request #59
Opened 2021-10-09 14:16 UTC by luffingluffy

2021-10-09 18:37 UTC, over-fitted requested changes

2021-10-09 18:37 UTC, over-fitted commented on src/main/java/seedu/address/model/person/Person.java
> +    public Person(Name name, Phone phone, Email email, Address homeAddress, Optional<Address> workAddress,
could probably have parameter type be address, then convert to optional in the constructor. This way you can use null as an argument as expected instead of Optional.empty()

2021-10-09 18:37 UTC, over-fitted commented on src/main/java/seedu/address/model/person/Person.java
> +        requireAllNonNull(name, phone, email, homeAddress, workAddress, quarantineAddress, tags);
workAddress and quarantineAddress can be null if we do optional conversion in constructor

2021-10-09 18:37 UTC, over-fitted commented on src/main/java/seedu/address/storage/JsonAdaptedPerson.java
> +        final Optional<Address> modelQuarantineAddress = Optional.ofNullable(workAddress).map(Address::new);
validation of workAddress values is not carried out. see:homeAddress validation

2021-10-10 05:13 UTC, wei2912 commented on src/main/java/seedu/address/model/person/Person.java
> +    public Person(Name name, Phone phone, Email email, Address homeAddress, Optional<Address> workAddress,
As discussed on the Telegram chat, we opted for use of the `Optional` monad to avoid any confusion over mixing of non-nullable parameters, e.g. `homeAddress`, with nullable parameters. Using `Optional` makes it explicit that these parameters can be either specified or left empty, which is much clearer.

2021-10-10 05:52 UTC, wei2912 commented on src/main/java/seedu/address/storage/JsonAdaptedPerson.java
> -                             @JsonProperty(value = "tagged", required = false) List<JsonAdaptedTag> tagged) {
Please undo these changes - will correct them during integration later!

2021-10-10 06:36 UTC, wei2912 approved these changes
LGTM!

2021-10-10 06:36 UTC, wei2912 commented on src/main/java/seedu/address/model/person/Person.java
> +    public Person(Name name, Phone phone, Email email, Address homeAddress, Optional<Address> workAddress,
Gonna break with protocol and resolve this conversation cos this PR will be merged into `add-command-v1.2` first. We can discuss this further in https://github.com/AY2122S1-CS2103-W14-2/tp/pull/61 if required!

2021-10-10 06:36 UTC, wei2912 commented on src/main/java/seedu/address/model/person/Person.java
> +        requireAllNonNull(name, phone, email, homeAddress, workAddress, quarantineAddress, tags);
See above comment on resolving conversations.

2021-10-10 06:37 UTC, merged