Implement TShiftCommand
AY2122S1-CS2103-W14-2/tp pull request #89
Opened 2021-10-19 22:14 UTC by frederickpek

Merging implements the TShiftCommand for v1.3 of Track2Gather, fixing #78. A sample user guide of the command is below.

**Command Word**: `tshift`

**Command Description**:
Shifts all persons' SHN end dates by the specified number of `DAYS`, postpones the date if the value is positive, brings forward the date if the value is negative. The SHN end dates will only be brought forward up to and including the pesons' SHN start date + 1.

**Format**: `tshift [PLUS_MINUS_SIGN]DAYS`
* `DAYS` should be a number between `1` and `90` inclusive.

**Example**:
* `tshift 3` postpones all SHN end dates by 3 days. This is identical to `tshift +3`.
* `tshift -3` brings forward all SHN end dates by up to 3 days.

2021-10-20 06:31 UTC, lrnshk commented on src/main/java/seedu/address/logic/commands/TShiftCommand.java
> +    public static final String MESSAGE_TSHIFT_PLUS_SUCCESS = "All SHN end date has been extended by %d days.";
End date is "pushed back/postponed", because I don't think a date can be "extended'

2021-10-20 06:36 UTC, lrnshk commented on src/main/java/seedu/address/logic/commands/TShiftCommand.java
> +                    personToEdit.getNextOfKinPhone(), personToEdit.getNextOfKinAddress());
Is it possible to do this using EditPersonDescriptor?

2021-10-20 06:37 UTC, lrnshk commented on src/main/java/seedu/address/logic/commands/TShiftCommand.java
> +        LocalDate minValidDate = startDate.plusDays(1);
Minor comment, but minValidStartDate?

2021-10-20 06:40 UTC, lrnshk commented on src/test/java/seedu/address/logic/commands/TShiftCommandTest.java
> +        TShiftCommand tshiftcommand = new TShiftCommand(days);
variable should be named tShiftCommand

2021-10-21 03:54 UTC, wei2912 requested changes
Looks good overall, I've requested a few minor changes.

On the functionality of the command, we may want to restrict the number of days (perhaps +- 8 weeks) so as to avoid issues with dates going too far back.

2021-10-21 03:54 UTC, wei2912 commented on src/main/java/seedu/address/logic/commands/TShiftCommand.java
> +            + "Example: " + COMMAND_WORD + " 3 ";
Just a small nitpick - there's a trailing space at the end of this string.

2021-10-21 03:54 UTC, wei2912 commented on src/main/java/seedu/address/logic/commands/TShiftCommand.java
> +    public static final String MESSAGE_TSHIFT_MINUS_SUCCESS = "All SHN end date has been brought forward by %d days.";
"SHN end date" should be plural.

2021-10-21 03:54 UTC, wei2912 commented on src/main/java/seedu/address/logic/commands/TShiftCommand.java
> +    public String getSuccessMessage() {
Consider employing defensive programming here by adding an assert for `days != 0`.

That said, I think it is okay to lump this method with the `execute` command since it's not complex and only makes sense in the context of execution.

2021-10-21 03:54 UTC, wei2912 commented on src/main/java/seedu/address/logic/commands/TShiftCommand.java
> +                    personToEdit.getNextOfKinPhone(), personToEdit.getNextOfKinAddress());
+1

2021-10-21 03:54 UTC, wei2912 commented on src/main/java/seedu/address/logic/commands/TShiftCommand.java
> +    }
Minor nitpick, but could this method follow the style of other commands, e.g. for `AddCommand`:

```java
    public boolean equals(Object other) {
        return other == this // short circuit if same object
                || (other instanceof AddCommand // instanceof handles nulls
                && toAdd.equals(((AddCommand) other).toAdd));
    }
```

2021-10-21 04:34 UTC, frederickpek commented on src/main/java/seedu/address/logic/commands/TShiftCommand.java
> +    public String getSuccessMessage() {
Sure, i think it makes sense to add that assertion.

Also, i wrote this method to support testing as well. It's inplace of the general `static final String MESSAGE_SUCCESS` pattern for each command. It wont apply here since each TShiftCommand's success mesage differs slightly based on the sign of its `days` attribute.

Would you rather i change it to a more generic command and follow that pattern instead? Perhaps something like `All SHN end dates have been shifted accordingly`.

2021-10-21 04:37 UTC, frederickpek commented on src/main/java/seedu/address/logic/commands/TShiftCommand.java
> +    }
Oops,  i just so happended to be referencing the equals method of `EditCommand` instead, which was the only command whose equals method was different from the rest LOL

2021-10-23 10:10 UTC, merged